# Generated by Django 5.0.4 on 2024-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirjasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laina',
            name='palautettu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
