# Generated by Django 5.0.4 on 2024-04-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirjasto', '0005_alter_laina_lainauspaiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirja',
            name='kansikuva',
        ),
    ]
